### ISSUE TITLE
Possible incorrect generators for Fd-3m

### ISSUE THREAD

**Issue by rowlesmr** [SpinW/spinw#109]
https://github.com/SpinW/spinw/blob/9e8a1ff80bf36105910eaf15f9b6e08b3d8c82b7/dat_files/symmetry.dat#L227

I was having a look and comparing the generators with yours and the Bilbao server, and the Bilbao values are different.

You have: `x+1/2,y,z+1/2;  x+1/2,y+1/2,z;`
Bilbao has: `x,y+1/2,z+1/2; x+1/2,y,z+1/2`

Is this just due to a difference in how you use the generator triplets?

**Comment by mducle** [comment]
@rowlesmr - yeah, it looks like a typo but then it should be changed for `F m -3 m`, `F m -3 c` and `F d -3 c` too. I'm not really sure how this came about or where these generator coordinates come from. Do the generated positions look correct for your system?

**Comment by rowlesmr** [comment]
I don't have any generated coordinates to match against; I was looking at projects which generated equivalent positions.

I'm putting together my own list, and saw that yours was different.

**Comment by mducle** [comment]
Check generated positions with current code and [VESTA](http://www.jp-minerals.org/vesta/en/) - generated positions agree despite differences in generators. Also checked the generated positions with the Bilbao generator expression (after applying this diff)

```diff
diff --git a/dat_files/symmetry.dat b/dat_files/symmetry.dat
index adbab7a..3ad5846 100644
--- a/dat_files/symmetry.dat
+++ b/dat_files/symmetry.dat
@@ -224,7 +224,7 @@
  224  P n -3 m   : -x+1/2,-y+1/2,z; -x+1/2,y,-z+1/2; z,x,y; y+1/2,x+1/2,-z; -x,-y,-z
  225  F m -3 m   : x+1/2,y+1/2,z; x+1/2,y,z+1/2; -x,-y,z; -x,y,-z; z,x,y; y,x,-z; -x,-y,-z
  226  F m -3 c   : x+1/2,y+1/2,z; x+1/2,y,z+1/2; -x,-y,z; -x,y,-z; z,x,y; y+1/2,x+1/2,-z+1/2; -x,-y,-z
- 227  F d -3 m   : x+1/2,y+1/2,z; x+1/2,y,z+1/2; -x+3/4,-y+1/4,z+1/2; -x+1/4,y+1/2,-z+3/4; z,x,y; y+3/4,x+1/4,-z+1/2; -x,-y,-z
+ 227  F d -3 m   : x,y+1/2,z+1/2; x+1/2,y,z+1/2; -x+3/4,-y+1/4,z+1/2; -x+1/4,y+1/2,-z+3/4; z,x,y; y+3/4,x+1/4,-z+1/2; -x,-y,-z
  228  F d -3 c   : x+1/2,y+1/2,z; x+1/2,y,z+1/2; -x+1/4,-y+3/4,z+1/2; -x+3/4,y+1/2,-z+1/4; z,x,y; y+3/4,x+1/4,-z; -x,-y,-z
  229  I m -3 m   : x+1/2,y+1/2,z+1/2; -x,-y,z; -x,y,-z; z,x,y; y,x,-z; -x,-y,-z
  230  I a -3 d   : x+1/2,y+1/2,z+1/2; -x+1/2,-y,z+1/2; -x,y+1/2,-z+1/2; z,x,y; y+3/4,x+1/4,-z+1/4; -x,-y,-z
```

The generated positions are the same (for a general position) for the original code as well as the change. 

Given this, will keep the generators as they are, as they do not affect the generated positions.
