### ISSUE TITLE
Doubt about notation used in anisotropic exchange interaction and single ion anisotropy.

### ISSUE THREAD

**Issue by LalitYadav07** [SpinW/spinw#139]
I have been recently using SpinW for modeling magnetic systems and I came across a situation where I need to define anisotropic exchange interactions. My magnetic ions are not located at the vertices of the unit cell, and the nearest neighbor bond is not in the crystallographic direction. I am confused about the coordinate system used by SpinW when defining anisotropic exchange interactions (Jx, Jy, Jz).

Is the anisotropic exchange interaction defined in the crystallographic coordinate system or a local coordinate system aligned with the bond direction? If it's in the local coordinate system, does SpinW automatically take care of the transformation between the crystallographic and local coordinate systems when defining the anisotropic exchange?

I would appreciate any clarification or guidance on this issue. If there are any resources or examples that explain the coordinate system handling for anisotropic exchange interactions in SpinW, please let me know.

I would also like to confirm whether the following definitions for in-plane and easy-axis anisotropy are accurate:
In-plane anisotropy in the xy-plane:
A_inplane = [-K 0 0; 0 -K 0; 0 0 0];, where K is a positive value.
Easy-axis anisotropy along the z-axis:
A_easyaxis = [0 0 0; 0 0 0; 0 0 -K];, where K is a positive value.
Alternatively, is it the case that the sign of K can be flipped to switch between easy plane and easy axis preferences?
Thank you for your support and assistance!

**Comment by mducle** [comment]
@LalitYadav07 Exchange interactions and anisotropy parameters in SpinW are defined in terms of a crystal Cartesian "xyz" coordinate system defined by:

_x_||_a_
_z_ perpendicular to _a_ and _b_
_y_ perpendicular to _x_ and _z_

with respects to the crystallographic directions _a_, _b_, and _c_.

This is global coordinate system - if you want a bond-directional coordinate system you'll need to transform it yourself unfortunately.

> Alternatively, is it the case that the sign of K can be flipped to switch between easy plane and easy axis preferences?

Yes, negative `K` indicates an easy-axis whilst positive `K` indicates an easy plane perpendicular to that direction.

If you plot the spinw model (e.g. `plot(swobj)`) you can see a faint ellipse around each atom if you have set the single-ion anisotropy. The ellipse will be highly elongated for an easy-axis (like in [tutorial 13](https://www.spinw.org/tutorials/13tutorial)) and more pancake-like for easy plane (like in [tutorial 12](https://www.spinw.org/tutorials/12tutorial)).

**Comment by mducle** [comment]
Closed as answered.
