### ISSUE TITLE
Error in spinw.fourier ( Unrecognized variable nMag0 )

### ISSUE THREAD

**Issue by KULDEEP-KARGETI** [SpinW/spinw#151]
Q = [0 1 0]
F = fourier( Cr, Q, 'isomode', 'auto')

While running this in MATLAB, I am getting error given below.

Unrecognized function or variable 'nMag0'

Error in spinw/fourier (line 292)
res.ft = ft*(nMag/nMag0);

Thank you For your suggestion.

**Comment by mducle** [comment]
@KULDEEP-KARGETI thanks for reporting this. I've just committed a fix. In the mean time you can use this file:

[fourier_m.zip](https://github.com/SpinW/spinw/files/13232332/fourier_m.zip)

(unzip and put it in the `swfiles/@spinw` folder of SpinW).
