### ISSUE TITLE
Excitation Spectrum of a 1D AF Heisenberg Chain.

### ISSUE THREAD

**Issue by hcut** [SpinW/spinw#165]
Hi

I was wondering how we can calculate the Excitation Spectrum of a 1D AF Heisenberg Chain.

Can we calculate the excitation spectrum of any 1D spin chain model ?

Thanks

**Comment by mducle** [comment]
@hcut Have a look at [tutorial 2](https://spinw.org/tutorials/02tutorial). 

Note that with linear spin wave theory you can only calculate the magnon spectra if there is magnetic ordering - e.g. you cannot calculate the spinon spectrum of a 1D chain with linear spin wave theory.
