### ISSUE TITLE
Mex post R2018b

### ISSUE THREAD

**Issue by wardsimon** [SpinW/spinw#17]
There are large error is the self consistency checks in post R2018a. The `useMex` option should be set to false if using an effected system.

**Comment by simonward86** [comment]
Original thoughts:

> I hope it's just a different compile flag - it should use the "largematrix" (or some such) flag since Matlab has decided to change the data layout for complex numbers with 2018b and also the default mex behavior for complex numbers (previously it was stored as the full real matrix followed by the full imaginary matrix, now it uses the FORTRAN and C++ default of storing each element as two numbers "interleaved").

Unfortunately a bit harder. See:

[https://uk.mathworks.com/matlabcentral/answers/390105-r2018a-complex-interleaved-data-is-the-new-memory-model](https://uk.mathworks.com/matlabcentral/answers/390105-r2018a-complex-interleaved-data-is-the-new-memory-model)

**Comment by simonward86** [comment]
Added a fallback and message so the post R2017b users can't use mex until this is sorted. Commit 2f27fff

**Comment by mducle** [comment]
This issue is no longer valid as we are planning to refactor the spinwave code into C++ entirely instead of just using mex files for the actual diagonalisation (leaving serial bottlenecks in calculating the Hamiltonian matrix).
