### ISSUE TITLE
Powder fitting feature request: Ability to mask data

### ISSUE THREAD

**Issue by mducle** [SpinW/spinw#185]
Requested by user V. Shroya (U. Warwick)

It would be nice if the [new powder fitting class](https://github.com/SpinW/spinw/pull/174) `sw_fitpowder` could include a mechanism to be able to mask some regions of data which SpinW does not / cannot simulate (e.g. elastic lines / Bragg peaks).

**Comment by RichardWaiteSTFC** [comment]
As discussed I'll put this in #174
