### ISSUE TITLE
optimaize antisymmetric interaction

### ISSUE THREAD

**Issue by mkmk0324** [SpinW/spinw#188]
Hello.
How can I optimize antisymmetric interactions?
For example, if I want to include the z component of the DM interaction,
D(matrix) = [0,D,0;-D,0,0;0,0,0]
but,
par_fit.func = @(obj,p)matparser(obj,'param',p,'mat',{****},'init',true);
What should I write in the **** part?
In other words, can I put a constraint condition (D(1,2)=-D(2,1)) on D(1,2) and D(2,1)?

Also, is there a solution if I want to put a constraint condition on more than three terms, like the xy component of the DM interaction?

**Comment by mducle** [comment]
@mkmk0324 You can use the `'selector'` argument of `matparser` as described in the [documentation](https://github.com/SpinW/spinw/blob/master/swfiles/%40spinw/matparser.m#L19-L25). E.g.

```
param = [J1, DM];
mat = {'J1', 'DM'};
sel = cat(3, eye(3), [0 1 0; -1 0 0; 0 0 0]);
par_fit.func = @(obj, p) matparser(obj, 'param', p, 'mat', mat, 'selector', sel, 'init', true);
```

Note that you have to give a selector matrix for _every_ parameter.

**Comment by mkmk0324** [comment]
Thank you for your prompt reply.
I understood. This is a very useful feature that can be extended to many different cases.
It was very helpful! Thanks.
