### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by stephall** [SpinW/spinw#19]
In the documentation of spinw/spinwave under Input Argument 'Q' is written:

For example to define a scan along $(h,0,0)$ from $h=0$ to $h=1$ using **200** $Q$ points the following input should be used:
Q = {[0 0 0] [1 0 0]  **50**}

=> Adjust to same number of Q points.

**Comment by simonward86** [comment]
Fixed in commit 15a3ae1 .
Thanks for the diligent checking :-)
