### ISSUE TITLE
Spinwave Spectra Error

### ISSUE THREAD

**Issue by GavinPhD** [SpinW/spinw#20]
Hello, I have run some fits of spin waves and I am now plotting the spectra with those parameters at a different field. This field happens to coincide with the spin wave bands touching zero energy, For some reason this gives an odd gap (shown in the figure below) at the zone center. Is there a reason for this or is it a bug?

![h10calcspectra](https://user-images.githubusercontent.com/48099176/53582894-aba0d980-3b3d-11e9-845e-7ae3bb5b0344.jpeg)

**Comment by simonward86** [comment]
Hey Gavin,
I'm guessing you have given the `'Evect'` option to `sw_egrid` and your energy vector is something like `0:0.001:1`. At your applied magnetic field has softened and is slightly negative. Hence it has not been convoluted with the energy Gaussian. This is my guess. Try plotting with out `sw_neutron` or `sw_egrid`, so you can see what the modes and  the imaginary components are doing.

**Comment by GavinPhD** [comment]
That seemed to be the issue. Thanks Simon!
