### ISSUE TITLE
Fractional occupancy

### ISSUE THREAD

**Issue by SrimalR** [SpinW/spinw#201]
Hi,

I am trying to calculate spin waves for a system with fractional occupancy using this code,

cnto = spinw;

cnto.genlattice('lat_const', [5.13860 5.13860 14.28570], 'angled', [90 90 120], 'sym', 'R -3');

cnto.addatom('r',[0 0 0.35200],'label','Co','occ',0.5,'formfact','MCo+2','S',1/2,'color','blue')
cnto.addatom('r',[0 0 0.35200],'label','Ni','occ',0.5,'formfact','MNi+2','S',1,'color','blue')

cnto.gencoupling('maxDistance', 8, 'forceNoSym',true);
plot(cnto, 'range',[1 1 1])..........

But I got this error, 

Error using spinw/gencoupling
Some atoms are too close (Dmin=0<0.5), check your crystal structure!

Error in CNTO (line 10)
cnto.gencoupling('maxDistance', 8, 'forceNoSym',true);
  

Is it possible in spinW to handle fractional occupancies with different spins?

**Comment by SrimalR** [comment]
Hi @mducle. Thank you for the response. This is an interesting way to do this. I will try this.

**Comment by SrimalR** [comment]
Hi @mducle . Is there a way to assign spins to this supercell type system. Do I need to do it manually one by one?
My system has in plane spin orientation with in plane FM interaction and out of plane AFM interactions.

**Comment by mducle** [comment]
@SrimalR 

For the spin orientations - it depends on whether the Ni spins are oriented differently from the Co spins. If you just have an averaged AFM structure (for example) then you can just input it before the section where the super cell is created and the "newcell" command will copy it onto the supercell. If the spin orientations of the Ni and Co are different then you'll have to assign it one by one in the loop.

For the interactions, you can check the bond table (produced by the last line in the code above) to see which one is in-plane and which is out-of-plane and adjust the values appropriately. (Positive numbers in the "addmatrix" command indicate antiferromagnetic interactions, negative are ferromagnetic).
