### ISSUE TITLE
Can't reproduce the spectrum in Tutorial 4

### ISSUE THREAD

**Issue by seuc** [SpinW/spinw#205]
Hi,
I am trying to understand tutorial 4 but when I run the code end up with the following error.

Warning: Eigenvectors of defective eigenvalues cannot be orthogonalised at some q-point! 
> In spinw/spinwave (line 1297)
In tutorial4 (line 54) 
Error using sw_egrid
The imaginary part of the spin wave energes is larger than the bin size! Improve your
calculation or disable imagChk option!

Error in tutorial4 (line 56)
sqSpec = sw_egrid(sqSpec,'Evect',linspace(0,6.5,500));

I am using Matlab R2023b on a MacOS.

**Comment by mducle** [comment]
@seuc Sorry there's been some changes in the code and the tutorial was not updated.

It will work if you change the second line of code from:

```
AFsq.genlattice('lat_const',[3 3 6],'angled',[90 90 90],'spgr',0)
```

to

```
AFsq.genlattice('lat_const',[3 3 6],'angled',[90 90 90])
```

(e.g. remove the `'spgr', 0` part).

I've updated the tutorial now.

**Comment by seuc** [comment]
I see. Thank you.
