### ISSUE TITLE
Inelastic Intensity Inconsistency

### ISSUE THREAD

**Issue by GavinPhD** [SpinW/spinw#21]
I have two plots (shown below) that seem to have a discrepancy for what the intensity should be at a given reciprocal lattice point (0,0,0). If you look at the [-HH0] slice below it is much higher intensity at H=0 then the [H00] slice below. Is there something in the way the spectra is being calculated that would cause this?

![mhh0calcspectra](https://user-images.githubusercontent.com/48099176/53585855-240a9900-3b44-11e9-888a-ff8122de4660.jpeg)
![h00calcspectra](https://user-images.githubusercontent.com/48099176/53585862-28cf4d00-3b44-11e9-82a1-cf8a5a52d9c0.jpeg)

**Comment by simonward86** [comment]
Hey Gavin, 
Is there any chance of getting the color bar to go along with the plots?
Also, in the `spectra` structure returned from `obj.spinwave` can you find the corresponding H=0 index in `index = all(spectra.hkl == [0 ; 0; 0], 1)` and check the difference in the `spectra.Sab(:,:,:,index)`. 
There is no reason why the intensities should be different as point calculation is non-contiguous, so I'm guessing something has happened with plotting.

**Comment by GavinPhD** [comment]
Hey Simon, 
Thanks for the quick response. I checked Sab for H=0 on both and they seem to have the same values (clips 1 and 2 below). After posting the plots above, I realized that I hadn't checked the color scale. Turns out they were different, however, remedying that did not fix the intensity discrepancy. I have included the plots with colorbars below.

H00 Sab and hkl values:
![h00](https://user-images.githubusercontent.com/48099176/53654309-a9588100-3c0a-11e9-898c-c1ed337d48ca.PNG)

H-H0 Sab and hkl values:
![mhh0](https://user-images.githubusercontent.com/48099176/53654374-ddcc3d00-3c0a-11e9-8db6-61ccb0e45990.PNG)


H00 Spectra with colorbar:
![h00calcspectra](https://user-images.githubusercontent.com/48099176/53654484-123ff900-3c0b-11e9-935c-faa70e7bd8bc.jpeg)

H-H0 Spectra with colorbar:
![mhh0calcspectra](https://user-images.githubusercontent.com/48099176/53654507-1c61f780-3c0b-11e9-8eda-f119376a807e.jpeg)

**Comment by simonward86** [comment]
Can you try:
```
spectra = obj.spinwave({[-1.5 0 0], [0 0 0], [1.5 -1.5 0], 301})
```
This will be traversing all Q vectors at once. Then:
```
spec = sw_neutron(spec);
spec = sw_egrid(spec,'component','Sperp')
figure;
sw_plotspec(spec)
```
This will give the correct output (I hope!). If it does, then the difference comes from either different components or convolution doing something with normalization.

**Comment by GavinPhD** [comment]
I ran the code you gave and got the left plot below, which looks fine. However, I found that when I enabled the g-tensor in obj.spinwave, I suddenly get the intensity discrepancy (right plot below), so it seems it may be deeper issue. 

![image](https://user-images.githubusercontent.com/48099176/53824535-64498d00-3f31-11e9-82d4-089a2b3586eb.png)

**Comment by simonward86** [comment]
Hey Gavin,
I've been looking into this and can see theoretically where it arises. Is it possible that you could email me the script so that I can do a bit more testing of the specific problem? Then I'll report back :-)

**Comment by simonward86** [comment]
I've played around with the code and think it is a peculiarity with the system, where there is a singularity at `[0, 0, 0]`. I cant say why it occurs, but if you look at the structure factor maps the same thing happens at `[0, 0, 0]` but along `[0, K, 0]` with out the g-factor albeit a far lesser extent.

**Horace code**

You can use  the Horace interface and play around with this and see if it makes sense.
     
```
horaceObj = d4d(obj.abc,[1 0 0 0],[-0.5,0.05,0.5],[0 1 0 0],[-0.5,0.05,0.5],[0 0 1 0],[-0.5,0.05,0.5],[0 0 0 1],[0,0.01,10]);
horaceObj = disp2sqw_eval(horaceObj,@obj.horace,{'component','Sperp','gtensor',true}, 0.09);
horaceObj2 = d4d(obj.abc,[1 0 0 0],[-0.5,0.05,0.5],[0 1 0 0],[-0.5,0.05,0.5],[0 0 1 0],[-0.5,0.05,0.5],[0 0 0 1],[0,0.01,10]);
horaceObj2 = disp2sqw_eval(horaceObj2,@obj.horace,{'component','Sperp','gtensor',false}, 0.09);
```

**`[H, K, 0]` plane**

| With g-factor | Without g-factor|
| --- | --- |
|![HK_plane_withG](https://user-images.githubusercontent.com/2798086/54363492-51d6fe00-466b-11e9-923f-0673485715cc.png) | ![HK_plane_withoutG](https://user-images.githubusercontent.com/2798086/54363493-51d6fe00-466b-11e9-815d-2199942fda61.png) |

**`[H, 0, L]` plane**

| With g-factor | Without g-factor|
| --- | --- |
|![HL_plane_withG](https://user-images.githubusercontent.com/2798086/54363495-51d6fe00-466b-11e9-9b61-29563877bfdd.png) | ![HL_plane_withoutG](https://user-images.githubusercontent.com/2798086/54363496-526f9480-466b-11e9-9ad0-602246648bdd.png)|

**`[0, K, L]` plane**

| With g-factor | Without g-factor|
| --- | --- |
|![KL_plane_withG](https://user-images.githubusercontent.com/2798086/54363497-526f9480-466b-11e9-97d5-357ff0029d85.png) | ![KL_plane_withoutG](https://user-images.githubusercontent.com/2798086/54363500-526f9480-466b-11e9-9847-1f55001caed2.png)|

**Comment by GavinPhD** [comment]
Thanks for looking into that, Simon. I am not sure why there would be a singularity at (0, 0, 0) for this system (as we definitely don't see one experimentally). If I happen to discover why that exists at some point I will let you know.
