### ISSUE TITLE
sw_plotspec sortMode documentation/code discrepancy 

### ISSUE THREAD

**Issue by g5t** [SpinW/spinw#22]
https://github.com/SpinW/spinw/blob/62308eefef4b31c11e344105b25401f140c90a14/swfiles/sw_plotspec.m#L74-L76 https://github.com/SpinW/spinw/blob/62308eefef4b31c11e344105b25401f140c90a14/swfiles/sw_plotspec.m#L193-L194
The default setting for `'sortMode'` contradicts the documentation in `sw_plotspec`.  While changing the documentation would solve the discrepancy, I think that changing the default to match the documentation is the better solution as it fixes the mode labeling issue for incommensurate orders.

Furthermore, the optional flag `'sortMode'` for `sw_plotspec` and, e.g., `spinwave`, have different meanings -- the first numerically sorts the mode energies at each **Q** to avoid plotted-crossings, while the second uses mode continuity at a crossing to assign energies to modes. Switching one or both flag names might help avoid any future confusion regarding what each does.

**Comment by simonward86** [comment]
Hey! Thanks for the input and documentation checking :-) 
I'll correct the documentation for the default option of  `sortMode` in `sw_plotspec`. As a compromise I'll extend the `sortMode` documentation to clarify the sorting methods as changing the option could cause errors on existing scripts. Or, I'll implement both and give a depreciation warning.
