### ISSUE TITLE
sw_update no longer working

### ISSUE THREAD

**Issue by mducle** [SpinW/spinw#25]
`sw_update` downloads a google doc (https://docs.google.com/uc?export=download&id=0BzFs7CQXhehSRXpjT0dndDNxNUE) in order to know where to download a new zip of spinw. However this document no longer exists.

**Comment by simonward86** [comment]
I've been meaning to rewrite the update mechanism but haven't gotten around to it. 
I'm currently thinking that the version file should be kept on the spinw.org repo and should link to a tagged release on github. 
Thoughts?

**Comment by mducle** [comment]
That sounds good to me!

**Comment by simonward86** [comment]
I'm remaking the build and unit test workflow at the moment. I'll add this as a sub-task so that it should auto generate on  a merge to the master branch.

**Comment by simonward86** [comment]
Fixed `sw_update` and it will go live (function and not throw errors) on the latest release
