### ISSUE TITLE
Update PySpinW

### ISSUE THREAD

**Issue by mducle** [SpinW/spinw#26]
Update PySpinW to no use `Transplant` / `ZeroMQ`.

**Comment by simonward86** [comment]
Pinging @mducle . 

I have wrote a MATLAB/Python interface which kinda works (no graphics yet, but I was going to re-write them in python anyway). See SpinW/pySpinW@7d0f17d795df00d910653f78e9cf335e3f02fb8e

This should work also for arbitrary MATLAB code

**Comment by wardsimon** [comment]
A complete re-write is scheduled for mid August->November

**Comment by rebeccafair** [comment]
Updated plan: https://github.com/SpinW/pySpinW/issues/2
