### ISSUE TITLE
Small bug in genlattice.m

### ISSUE THREAD

**Issue by kspark2237** [SpinW/spinw#28]
Dear Simon,

https://github.com/SpinW/spinw/blob/af6b705c8d2c7f54c54debb19e32e96bc465d5a7/swfiles/%40spinw/genlattice.m#L177

I think above code should be changed as following:
obj.lattice.angle     = [angle2(b,c),angle2(a,c),angle2(a,b)];

Best regards,
Kisoo

**Comment by simonward86** [comment]
Hey, 
Yep, you are totally correct. I have pushed the changes to the development branch

**Comment by simonward86** [comment]
Will merge into master at next point release.
