### ISSUE TITLE
YIG example (Tutorial 21) not reproducible in MacOS

### ISSUE THREAD

**Issue by martin-rv** [SpinW/spinw#32]
Dear Simon,

I tried to reproduce the results shown in Tutorial #21, where the spinwave spectrum off YIG is calculated. However, my results do not match the tutorial results. I am running Matlab in MacOS. 

Thank you,
Martin

**Comment by pastle** [comment]
Hi Martin, can you specify the difference? I tried the tutorial and it works perfect for me.

**Comment by martin-rv** [comment]
Hi Shang Gao,

I am not able to reproduce the spin density wave spectrum. I attach here my
result. I had communications with Simon, and I think he tried to run it on
MacOS and could not reproduce it either.

Did you run it on MacOS or Windows?

Best,
Martin

**Comment by pastle** [comment]
Hi Martin, the system I'm using is macOS High Sierra v10.13.6. My Matlab version is 2018a.

**Comment by martin-rv** [comment]
Hi Shang Gao,

Thank for checking. This is pretty strange. I am using MacOS Mojeva 10.14.5 and your same Matlab. 

As far as I understood, Simon Ward was had the same issue on MacOS. Are you aware? 

Best,
Martin

**Comment by martin-rv** [comment]
Hi Shang Gao,

Is this issue still open?

Best,
Martin

**Comment by pastle** [comment]
Hi Martin, I will run the script on Mojeva and see what happens.

**Comment by martin-rv** [comment]
Hi Shang Gao,

Did it work for you?

**Comment by wardsimon** [comment]
Far too late, but I've confirmed that this works. It might have been a problem with mexing on post R2018b MATALB. This option should now be disabled.
