### ISSUE TITLE
Inquiry about magnon dispersion calculation with anisotropy energy

### ISSUE THREAD

**Issue by kkang14** [SpinW/spinw#45]
Dear SpinW team,

Hope you all stay well and healthy.
I have an inquiry about magnon dispersion calculation with anisotropy energy.

I am working on the calculation for the magnon dispersion of antiferromagnetic MnPt.
Since MnPt has the uniaxial anisotropy, I add the anisotropy energy.
But, it seems the calculated magnon dispersion shows the opposite change comparing to what I expected.

https://drive.google.com/file/d/1tVOppQfh63pfVqZkR0C6ieGh7uW_AlOu/view?usp=sharing

When I add the easy axis, SpinW detected anisotropy well in the structural figure but it shows the collapse of magnon dispersion at Gamma point.
People commonly think that there should be a gap at the Gamma point due to the introduction of anisotropy energy.
When I try the easy plane, it shows the result which I expected with an easy axis case.

I found the same problem with different materials.
Does this opposite behavior happen because this is the antiferromagnetic material?

I am looking forward to hearing your answers.
Thank you in advance.

Yours Sincerely,
Kisung Kang

Ph.D. Candidate, Graduate Research Assistant
The Schleife Group
The Department of Materials Science and Engineering
University of Illinois at Urbana-Champaign

**Comment by pastle** [comment]
Can you upload your script?

**Comment by kkang14** [comment]
Thank you for your response!
Here is my script.

https://drive.google.com/file/d/1-JPHLhEPHuvpu1Ur4fKZZi0omzhOu4J9/view?usp=sharing

**Comment by pastle** [comment]
The input magnetic structure is not the ground state of the Hamiltonian. You can still perform some calculations by assigning 'hermit' to 'false' as you did in the script, but the calculated results are not very meaningful, especially at low energies.

**Comment by kkang14** [comment]
In that case, should I need to optimize the magnetic structure?
Does it possibly solve the problem?

**Comment by pastle** [comment]
Yes, you can. But normally the magnetic structure is known from neutron diffraction and it is the unknown coupling parameters that need adjustments.

**Comment by kkang14** [comment]
I used the magnetic structure from neutron diffraction.
Is it still needed to add any coupling parameters?
The exchange coefficient and anisotropy energy are originated from DFT calculations.

**Comment by pastle** [comment]
Probably yes. Also there might be uncertainties in the DFT calculations. You need to adjust the coupling parameters to find out the correct regime.

**Comment by kkang14** [comment]
Ah, I see. I will try the optimization.
Thank you for your advice!

**Comment by kkang14** [comment]
I think I solve the problem with the optimization step.
Thank you so much for your support!

Yours Sincerely,
Kisung Kang
