### ISSUE TITLE
Has SpinW considered the spin wave damping in simulating the SW intensity?

### ISSUE THREAD

**Issue by whilecloud1978** [SpinW/spinw#51]
Dear SpinW team,
            I have a basic question to ask. Can the SpinW simulate the spin wave intensity well when there is strong spin wave damping near magnetic zone boundary? In this case, the spin wave intensity becomes very low or invisible near zone boundary from the experimental observation. I succeeded in using SpinW to get a good fit on the dispersions on a few directions. However, the simulation using SpinW shows that the SW intensity at zone boundary has comparable intensity to that near zone center, as shown in the attached figure. This is inconsistent with the experimental SW intensity where it is invisible near zone boundary. I worried that if the fitted Js are incorrect since the simulated SW intensity is inconsistent with the experiment results.  How does SpinW simulate the SW intensity properly?
    Could you please advise me?  Thanks so much for your attention to my question.
![SWintensity](https://user-images.githubusercontent.com/75689212/101525285-16a95200-3959-11eb-9ee3-b192c2ee6b76.PNG)

**Comment by mducle** [comment]
Hi @whilecloud1978 - `spinW` does not calculate the spin wave damping. I think that in *linear* spin wave theory you cannot have any damping terms - in this (QM / ladder operator based) picture, damping comes from multi-magnon interactions and we consider only the single-magnon term here. Spin wave theory can be extended beyond the linear terms but I'm not sure there is a general way to do this - I think you have to consider specific lattices. For this reason (as well as a lack of time) we haven't implemented any thing like this in `spinW`.

On the other hand you can include the damping more easily using a Landau-Lifshitz equation of motion approach - I would recommend that you use the `UppASD` program: https://github.com/UppASD/UppASD which has a Python interface. In principle you can use the same exchange parameters in `UppASD` and `spinW` but as you say the actual dispersion (and certainly the intensities) will likely be different at the zone boundaries depending on the damping.

**Comment by whilecloud1978** [comment]
Dear @mducle ,
     Thanks so much for your detailed advice! I really appreciate it. That means the inconsistent simulation on SW intensity does not indicate that the obtained Js are incorrect.  Thanks.
