### ISSUE TITLE
SW dispersion in a helimagnet

### ISSUE THREAD

**Issue by YuliiaTymoshenko** [SpinW/spinw#53]
Dear SpinW team, 

I have rather basic question about a SW dispersion (I am talking about a dispersion, not about a neutron spectra) in a helimagnet. I've attached a simple example - dispersion curve in a symmetric helimagnet with 1 magnetic ion per unit cell. When we calculate it we use a rotating coordinate frame. As a result, moving back to the laboratory frame we get two magnon dispersion curves centered at +/- Q. How do we get the third replica centered at q=0 (red curve in the picture)? To which kind of excitations does it correspond?

Thank you very much in advance!
[SymJ1_m1J20p5.pdf](https://github.com/SpinW/spinw/files/5760196/SymJ1_m1J20p5.pdf)

**Comment by mducle** [comment]
Hi @YuliiaTymoshenko sorry I saw this at New Year's but then forgot about it until I saw it again just now.

Without knowing a bit more about the details of the system (the magnetic structure and exchanges), it's a bit difficult to say exactly what's happening in your case, but I think that the q=0 curve is what you would get if the spin *deviations* (or precession) is "ferromagnetic". I'm assuming that you've got a magnetic structure where the spins are all coplanar and the plane perpendicular is along the propagation direction (`a` in this case I guess). In this case, one set of the out-of-plane (deviations along `a`) modes would precess in-phase and give you the q=0 mode. However, this mode is parallel to `q` so you wouldn't see it in neutron scattering... maybe you can do a `sw_plotspec(sw_neutron(sw_egrid(spec, 'Evect', linspace(0,2,0.01))))` or something to see if the q=0 mode has any neutron intensity? For the other modes, I think they are precessions within the spin plane, which are perpendicular to `q`, but in this case for a helimagnet where the spins on neighbouring sites are rotated with respects to each other on this plane, the spin deviations would also have this periodicity.

Not sure if the above is clear enough... I admit to being a bit confused myself... sorry.
