### ISSUE TITLE
sw_fstat

### ISSUE THREAD

**Issue by manish9909** [SpinW/spinw#60]
I am having a problem using the function sw_fstat;  Could you explain how to set and what are the dimension of the following parameters.

parIn; T; E; M; nExt

parOut = sw_fstat(1, 'parIn', T, E, M, nExt)

TIA,

**Comment by wardsimon** [comment]
`sw_fstat` should not be called by itself, it is a helper function for `@spinw/anneal`. 

I've not used it however the help seems quite extensive. The source can be found [here](https://github.com/SpinW/spinw/blob/master/swfiles/%40spinw/anneal.m)

**Comment by mducle** [comment]
@manish9909 sorry this is very late, but if you want more information, you can look at [this presentation](https://github.com/pace-neutrons/edatc/blob/main/presentations/edatc21_slides_07_spinw2.pptx) (download it) around slide 18.

**Comment by manish9909** [comment]
Thanks for the presentation link. It's very helpful.
