### ISSUE TITLE
lattice vector in Triangular lattice

### ISSUE THREAD

**Issue by qtsearcher** [SpinW/spinw#64]
Hi, I am following tutorial 12 to build a triangular lattice. I am confused about this command: tri.genlattice('lat_const',[3 3 4],'angled',[90 90 120])
From the command, it seems a lattice of a=b\=c, a perpendicular to b, and 120 degrees with c. But the output is a=b\=c, and a has a 120 degree with b. In general, I am confused about where to put the right positions of the variables in the commands. I need to add more atoms based on this lattice, so knowing which variables correspond to which lattice vector is very important to me. Many thanks!

**Comment by mducle** [comment]
@qtsearcher - we're using the standard crystallographic notation where the `angled` values represent the angles `alpha`, `beta`, `gamma` where `alpha` is the angle between `b` and `c`, `beta` is the angle between `a` and `c` and `gamma` is the angle between `a` and `b`... it's not the angle of the axes w.r.t. to a Cartesian system.

You can find the documentation [here](https://spinw.org/spinw_genlattice) or type `help spinw/genlattice` in Matlab.

(Also in your case, `a=3`, `b=3` and `c=4` so it's not `a=b=c`.)
